# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- bash: az --version
  displayName: 'Show Azure CLI version'
  
# Get Acces Token
- bash: echo "##vso[task.setvariable variable=sauce]az account get-access-token --query 'accessToken'"
