# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


steps:
- bash : $a = az login --service-principal -u 181aded9-0234-4302-b731-935d818fc2a4 -p 4xP8Q~_Fq6gaHqUQWZ8lWdnAdwEbk.TOlmLXpb~p --tenant a48559b2-7a99-486c-813b-8e001def6ed5
  name: setvarStep
- script: echo $(setvarStep.myOutputVar)
  name: echovar
